# Use an official Ubuntu 18.04 runtime as a parent image
FROM ubuntu:bionic


RUN apt-get update && \
apt-get dist-upgrade -y && \
apt-get install curl python3 python3-dev -y && \
curl https://bootstrap.pypa.io/get-pip.py -o /root/get-pip.py && \
$(which python3) /root/get-pip.py && \
$(which pip3) install ansible

# Generate the inventory files
RUN mkdir -p /etc/ansible/ && echo "[local]\nlocalhost ansible_connection=local\n\n[ubuntu-bionic]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# using cat at the ENTRYPOINT keeps the container running so we can execute commands against it
ENTRYPOINT ["cat"]
