---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  # Roles IMPORTED (not included) in this fashion will have variables overridden
  # AND PERSISTED throughout the rest of the playbook
  vars:
    playbook: &playbook "{{ active_playbook }}"
    tests: "{{ active_test_file | default(active_playbook, true)}}"

  # tasks:
  #
  #   - name: "Import {{ playbook }}.yml tasks"
  #     import_tasks: "~/Projects/ansible-roles/ansible-role-nvm/molecule/default/playbook_{{ playbook }}.yml"
  #

  tasks:

    - name: "Import {{ tests }}.yml tests"
      import_tasks: ../tests/tests_{{ tests }}.yml

    - debug: var=vars
